theme: jekyll-theme-minimal
title: Mohammad Safayet Khan
description: "Welcome to my personal website!"

# Navigation menu (Tabs)
navbar:
  - title: "About"
    url: "#about"
  - title: "Education"
    url: "#education"
  - title: "Research Experience"
    url: "#research-experience"
  - title: "Honors and Awards"
    url: "#honors-and-awards"
  - title: "Technical Projects"
    url: "#technical-projects"
  - title: "Contact"
    url: "#contact"

